---
abstract: 'Serve static files with unique URLs and far-future expiry'
author:
  - 'Grant McLean <grantm@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-CDN
requires:
  Dancer: 0
  HTTP::CDN: 0
  HTTP::Date: 0
  perl: 5.010
resources:
  bugtracker: https://github.com/grantm/Dancer-Plugin-CDN/issues
  repository: git://github.com/grantm/Dancer-Plugin-CDN.git
version: 1.001
